'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import {Bot,Send,X,Sparkles,Loader2,Trash2,Copy,RotateCcw,Maximize2,Minimize2,ChevronDown,Check,Lightbulb,ArrowUpRight} from 'lucide-react';
import toast from 'react-hot-toast';

type Message={role:'user'|'assistant';text:string;time:number};
const defaults=['How can I improve my ATS score?','What should I do next?','What should I do about a missing skill?','How should I prepare for my interview?'];
const pagePrompts:Record<string,string[]>={
 '/workspace':['Analyze this job for me','What are my biggest skill gaps?','Which tool should I use next?'],
 '/optimizer':['Explain my ATS score','What keywords am I missing?','Which changes are safest?'],
 '/resume-builder':['Improve my resume summary','Make my project bullets stronger','What should I change for ATS?'],
 '/interview-prep':['Give me a mock interview question','How should I answer technical questions?','Review my interview strategy'],
 '/career-gaps':['Which gap should I fix first?','Suggest a project for my gaps','How can I become job-ready faster?'],
 '/tracker':['What should I follow up on?','How can I improve my application funnel?','What should I do next?'],
};
function formatText(text:string){return text.split(/\n+/).map((line,i)=><span key={i} className="block">{line||' '}</span>)}
export default function CopilotChat(){
 const pathname=usePathname();
 const [open,setOpen]=useState(false); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [expanded,setExpanded]=useState(false); const [copied,setCopied]=useState<number|null>(null);
 const [messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Hi! I’m your Career Copilot. I can help you improve resumes, understand ATS results, close skill gaps, prepare for interviews, and plan your next job-search step.',time:Date.now()}]);
 const endRef=useRef<HTMLDivElement>(null); const inputRef=useRef<HTMLInputElement>(null);
 const prompts=useMemo(()=>pagePrompts[pathname]||defaults,[pathname]);
 useEffect(()=>{if(open) setTimeout(()=>inputRef.current?.focus(),80)},[open]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[messages,loading]);
 const send=async(text=input)=>{const q=text.trim();if(!q||loading)return;setInput('');setMessages(m=>[...m,{role:'user',text:q,time:Date.now()}]);setLoading(true);try{const history=messages.slice(-6).map(({role,text})=>({role,text}));const r=await fetch('/api/ai-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,history,page:pathname})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Assistant unavailable');setMessages(m=>[...m,{role:'assistant',text:d.answer||'I could not generate an answer.',time:Date.now()}]);}catch(e:any){toast.error(e.message||'Assistant unavailable.');}finally{setLoading(false)}};
 const clear=()=>{setMessages([{role:'assistant',text:'Chat cleared. What would you like to work on?',time:Date.now()}]);setInput('');};
 const copy=(text:string,index:number)=>{navigator.clipboard?.writeText(text);setCopied(index);setTimeout(()=>setCopied(null),1400);};
 return <>
  <button onClick={()=>setOpen(true)} aria-label="Open Career Copilot assistant" className="copilot-launch fixed bottom-5 right-5 z-40 group inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-3 text-sm font-black text-white shadow-[0_14px_40px_rgba(15,23,42,.22)] hover:-translate-y-0.5 hover:shadow-2xl print:hidden">
   <span className="relative grid h-5 w-5 place-items-center"><Bot size={18}/><span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-emerald-400 ring-2 ring-slate-950"/></span> Copilot <ArrowUpRight size={14} className="opacity-60 group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/>
  </button>
  {open&&<div className={`fixed inset-x-3 bottom-3 z-50 mx-auto flex ${expanded?'h-[min(780px,calc(100vh-1.5rem))] max-w-2xl':'h-[min(700px,calc(100vh-1.5rem))] max-w-md'} flex-col overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-[0_24px_80px_rgba(15,23,42,.24)] print:hidden sm:right-5 sm:left-auto sm:mx-0`}>
   <div className="relative overflow-hidden bg-slate-950 px-5 py-4 text-white"><div className="absolute -right-10 -top-16 h-36 w-36 rounded-full bg-blue-500/20 blur-2xl"/><div className="relative flex items-center justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-blue-600 shadow-lg shadow-blue-900/30"><Sparkles size={18}/></span><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate font-black">Career Copilot</p><span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-2 py-0.5 text-[9px] font-black uppercase tracking-wider text-emerald-300">AI</span></div><p className="text-xs text-slate-300">Context-aware career guidance</p></div></div><div className="flex items-center gap-1"><button onClick={()=>setExpanded(v=>!v)} className="hidden rounded-lg p-2 hover:bg-white/10 sm:block" aria-label={expanded?'Minimize chat':'Expand chat'}>{expanded?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button><button onClick={clear} className="rounded-lg p-2 hover:bg-white/10" aria-label="Clear chat"><Trash2 size={16}/></button><button onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-white/10" aria-label="Close chat"><X size={18}/></button></div></div><div className="relative mt-3 flex items-center gap-2 text-[10px] text-slate-300"><span className="rounded-full bg-white/10 px-2.5 py-1 font-bold">Current page: {pathname==='/'?'Home':pathname.split('/')[1]?.replaceAll('-',' ')||'Career Copilot'}</span><span className="hidden sm:inline">•</span><span className="hidden sm:inline">Evidence-aware answers</span></div></div>
   <div className="flex-1 space-y-4 overflow-y-auto bg-slate-50/70 p-4 sm:p-5"><div className="rounded-2xl border border-blue-100 bg-white p-3 shadow-sm"><div className="flex items-start gap-2.5"><Lightbulb size={16} className="mt-0.5 shrink-0 text-blue-600"/><div><p className="text-xs font-black text-slate-800">Quick start</p><p className="mt-0.5 text-[11px] leading-5 text-slate-500">Pick a suggestion or ask anything about your job search.</p></div></div></div>
    {messages.map((m,i)=><div key={`${m.time}-${i}`} className={`group flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`relative max-w-[90%] rounded-2xl px-4 py-3 text-sm leading-6 shadow-sm ${m.role==='user'?'rounded-br-md bg-blue-600 text-white':'rounded-bl-md border border-slate-200 bg-white text-slate-700'}`}><div>{formatText(m.text)}</div><div className={`mt-2 flex items-center gap-2 text-[9px] ${m.role==='user'?'justify-end text-blue-100':'text-slate-400'}`}><span>{new Date(m.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span>{m.role==='assistant'&&<button onClick={()=>copy(m.text,i)} className="inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 hover:bg-slate-100" aria-label="Copy response">{copied===i?<Check size={10}/>:<Copy size={10}/>} {copied===i?'Copied':'Copy'}</button>}</div></div></div>)}
    {loading&&<div className="flex"><div className="rounded-2xl rounded-bl-md border border-slate-200 bg-white px-4 py-3 text-sm text-slate-500 shadow-sm"><span className="mr-2 inline-flex gap-1 align-middle"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-slate-400"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-slate-400 [animation-delay:120ms]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-slate-400 [animation-delay:240ms]"/></span>Thinking through your question...</div></div>}
    {messages.length===1&&<div className="grid gap-2 sm:grid-cols-2">{prompts.map(q=><button key={q} onClick={()=>send(q)} className="group rounded-2xl border border-slate-200 bg-white px-3 py-3 text-left text-xs font-bold text-slate-600 shadow-sm hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50/50 hover:text-blue-700"><span className="flex items-center justify-between gap-2">{q}<ChevronDown size={14} className="-rotate-90 shrink-0 text-slate-300 group-hover:text-blue-500"/></span></button>)}</div>}
    <div ref={endRef}/></div>
   <div className="border-t border-slate-200 bg-white p-3 sm:p-4"><form onSubmit={e=>{e.preventDefault();send()}} className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-1.5 shadow-inner focus-within:border-blue-300 focus-within:bg-white focus-within:ring-4 focus-within:ring-blue-50"><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask your career question..." aria-label="Career Copilot message" className="min-w-0 flex-1 bg-transparent px-2 py-2 text-sm text-slate-800 placeholder:text-slate-400 outline-none"/><button type="submit" disabled={!input.trim()||loading} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-600 text-white shadow-sm hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-40" aria-label="Send message"><Send size={16}/></button></form><div className="mt-2 flex items-center justify-between px-1"><p className="text-[10px] text-slate-400">AI can be wrong. Verify important decisions.</p>{messages.length>1&&<button onClick={()=>send('Give me a concise next step based on our conversation.')} disabled={loading} className="hidden items-center gap-1 text-[10px] font-black text-blue-600 hover:text-blue-700 sm:inline-flex"><RotateCcw size={11}/> Next step</button>}</div></div>
  </div>}
 </>;
}
