'use client';
import {useState} from 'react';
import {FileText, Upload, Loader2} from 'lucide-react';
import toast from 'react-hot-toast';

type Props={value:string;onChange:(value:string)=>void;label?:string;placeholder?:string;rows?:number};
export default function ResumeInput({value,onChange,label='Resume',placeholder='Paste resume text or upload a PDF...',rows=14}:Props){
 const [fileName,setFileName]=useState(''); const [loading,setLoading]=useState(false);
 const handleFile=async(file:File)=>{const allowed=['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain'];if(!allowed.includes(file.type)&&!(/\.(pdf|docx|txt)$/i.test(file.name)))return toast.error('Please upload a PDF, DOCX or TXT resume.');if(file.size>10*1024*1024)return toast.error('Resume file must be 10 MB or smaller.');setFileName(file.name);setLoading(true);const form=new FormData();form.append('file',file);try{const r=await fetch('/api/parse-resume',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not parse resume.');onChange(d.text||'');toast.success(`${file.name} imported successfully.`);}catch(e:any){toast.error(e.message||'Could not parse the resume.');}finally{setLoading(false)}};
 return <div><div className="flex items-center justify-between gap-2"><label className="font-black">{label}</label><span className="text-xs text-slate-400">{value.trim().split(/\s+/).filter(Boolean).length} words</span></div><textarea value={value} onChange={e=>onChange(e.target.value)} rows={rows} placeholder={placeholder} className="mt-3 w-full rounded-xl border p-4"/><div className="mt-3 flex flex-wrap items-center gap-3"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-bold hover:bg-slate-50"><Upload size={16}/> Upload Resume PDF / DOCX / TXT<input type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" className="hidden" onChange={e=>e.target.files?.[0]&&handleFile(e.target.files[0])}/></label>{fileName&&<span className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500"><FileText size={14}/>{fileName}</span>}{loading&&<span className="text-xs font-semibold text-blue-600"><Loader2 size={14} className="mr-1 inline animate-spin"/>Parsing resume...</span>}</div></div>
}
